### ISSUE TITLE
Error 10000

### ISSUE THREAD

**Issue by Temeramor** [offici5l/MiBypassTool#1]
It doesn't work, unfortunately,
 gives an error.

code: 10000
description: 参数异常
descCN: 参数异常
descEN: Request parameter error

![1](https://github.com/offici5l/MiBypassTool/assets/53129286/daff528f-e721-4dd6-88f8-2e1c7171186c)

**Comment by Temeramor** [comment]
Nope, I can't downgrade Settings.apk - the app crashes when I go into developer mode :(

**Comment by LeanFly** [comment]
> try https://github.com/offici5l/MiBypassTool/releases/download/1/Settings.apk.zip

I installed the settings apk, and I can't enter the developer mode when I click the developer mode.

**Comment by offici5l** [comment]
device name ?
