### ISSUE TITLE
code: 30001

### ISSUE THREAD

**Issue by TimonDV27** [offici5l/MiBypassTool#2]
i have some troubles

[Settings.apk.zip](https://github.com/offici5l/MiBypassTool/releases/download/1/Settings.apk.zip) i tried, not helped

Now bind your account in Mi Unlock status ...

version: V816.0.31.0.UNCCNXM

change version to: V14.0.31.0.UNCCNXM

code: 30001

description: 绑定失败，请前往小米社区内测中心申请授权后重试

descCN: 绑定失败，请前往小米社区内测中心申请授权后重试

descEN: Couldn't add. Please go to Mi Community to apply for authorization and try again.

![2](https://github.com/offici5l/MiBypassTool/assets/93191844/0f70c2ba-d04c-43c4-8e12-0b882cc2e772)

**Comment by darkmanlv** [comment]
same error here, code: 30001

**Comment by offici5l** [comment]
Modern devices that come with the HyperOS system pre-installed currently cannot bypass their restrictions, but perhaps this will be possible in the future... tks 🙏.
