### ISSUE TITLE
There is a progress definetely, respect to the developer

### ISSUE THREAD

**Issue by battleabdi** [offici5l/MiBypassTool#5]
Because now it says "Couldn't verify, please try again later", and it turns of mobile network and does something, Usually when the mobile data is off it says "Connect to the network and try again". I have an issue with the settings apps version, dowloading the one that it suggested and we'll see how it goes. But this developer i appreciate his work. Redmi Note 13 pro garnet china mainland version, no one pulled off something like this so far, very cool man respect to you

**Comment by offici5l** [comment]
I just wanted to let you know that currently, it's not possible to bypass the restrictions of the Redmi Note 13 series devices, but perhaps this will be possible in the future.

tks🙏

**Comment by samson3221** [comment]
Hey, have you tried installing the "Settings.apk" on your device? The same happened to me and python instantly closed but it tells you to downgrade your software with "Settings.apk" before closing
