### ISSUE TITLE
Bypassing does not work

### ISSUE THREAD

**Issue by samson3221** [offici5l/MiBypassTool#6]
"_Cant add more accounts to this SIM Card_" **did** get bypassed, but now I still get:
 "_Couldn't add. Please go to Mi Community to apply for authorization and try again_"
 
 I tried running _MiBypassTool.py_ constantly while my phone was rebooting, but I'm not smart enough to get it to work.
 Thanks for making this anyway, since now I just have to wait 30 days to unlock it in the mi community.

The tutorial is pretty short too, like no information on when to run the code (_should phone be off?_) or if usb debugging has to be enabled and shit.

**Comment by offici5l** [comment]
I have added a new option:

━ 3 Bypass Both Restrictions
(Apply both bypasses)

note: that if your device was made directly with HyperOS from the factory, bypassing the restrictions is currently not possible.

and tks for your suggestion..

**Comment by samson3221** [comment]
Hey quick update, my problem was that python was closing the instant I opened it, that was because "pip" was not recognized as an internal or external command, and all i had to do is add it with cmd: "setx PATH "%PATH%;C:\Users\User\AppData\Local\Programs\Python\Python312\Scripts""

But even with python running, it still sadly does **not** unlock the mi status, it just says that it failed and I have to wait one to two minutes, I have a Redmi 12 btw and it is registered in west-europe
